version: "3"
services:
  db:
    image: "mysql:8.0.26"
    container_name: mysql-elementary
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
